In [1]:
import pandas as pd
heart_disease=pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [2]:
x=heart_disease.drop("target", axis=1)
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [3]:
y=heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [4]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
clf

RandomForestClassifier()

In [5]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test=train_test_split(x,y, test_size=0.2)

In [7]:
clf.fit(x_train, y_train);

In [8]:
y_preds=clf.predict(x_test)

In [9]:
y_preds

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [10]:
clf.score(x_test, y_test)

0.8360655737704918

In [11]:
clf.score(x_train, y_train)

1.0

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [13]:
print(classification_report(y_test, y_preds)) 

              precision    recall  f1-score   support

           0       0.83      0.77      0.80        26
           1       0.84      0.89      0.86        35

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61



In [14]:
confusion_matrix(y_test, y_preds) 

array([[20,  6],
       [ 4, 31]], dtype=int64)

In [15]:
accuracy_score(y_test, y_preds) 

0.8360655737704918

In [16]:
import numpy as np
np.random.seed(0)
for i in range (10, 100, 10):
    clf=RandomForestClassifier(i).fit(x_train, y_train) # clf store best logic made by random forest
    print(f"The accuracy with {i} numbers of trees is {clf.score(x_test, y_test)*100}")

The accuracy with 10 numbers of trees is 80.32786885245902
The accuracy with 20 numbers of trees is 80.32786885245902
The accuracy with 30 numbers of trees is 80.32786885245902
The accuracy with 40 numbers of trees is 80.32786885245902
The accuracy with 50 numbers of trees is 83.60655737704919
The accuracy with 60 numbers of trees is 83.60655737704919
The accuracy with 70 numbers of trees is 85.24590163934425
The accuracy with 80 numbers of trees is 83.60655737704919
The accuracy with 90 numbers of trees is 81.9672131147541


In [60]:
table=pd.read_csv("car-sales.csv")
table=table.head()
table
dummies1=pd.get_dummies(table.Make)
dummies2=pd.get_dummies(table.Colour)

In [61]:
dummies1

BMW  Honda  Nissan  Toyota
0    0      1       0       0
1    1      0       0       0
2    0      1       0       0
3    0      0       0       1
4    0      0       1       0

In [62]:
dummies2

Blue  White
0     0      1
1     1      0
2     0      1
3     0      1
4     1      0

In [63]:
table_dummies=pd.concat([table, dummies1], axis="columns")
table_dummies=pd.concat([table_dummies, dummies2], axis="columns")
table_dummies

Make Colour  Odometer (KM)  Doors  Price  BMW  Honda  Nissan  Toyota  \
0   Honda  White          35431      4  15323    0      1       0       0   
1     BMW   Blue         192714      5  19943    1      0       0       0   
2   Honda  White          84714      4  28343    0      1       0       0   
3  Toyota  White         154365      4  13434    0      0       0       1   
4  Nissan   Blue         181577      3  14043    0      0       1       0   

   Blue  White  
0     0      1  
1     1      0  
2     0      1  
3     0      1  
4     1      0

In [64]:
table_dummies=table_dummies.drop(["Colour", "Blue", "Toyota", "Make"], axis="columns")
table_dummies

Odometer (KM)  Doors  Price  BMW  Honda  Nissan  White
0          35431      4  15323    0      1       0      1
1         192714      5  19943    1      0       0      0
2          84714      4  28343    0      1       0      1
3         154365      4  13434    0      0       0      1
4         181577      3  14043    0      0       1      0

In [65]:
x=table_dummies.drop("Price", axis="columns")
x

Odometer (KM)  Doors  BMW  Honda  Nissan  White
0          35431      4    0      1       0      1
1         192714      5    1      0       0      0
2          84714      4    0      1       0      1
3         154365      4    0      0       0      1
4         181577      3    0      0       1      0

In [66]:
y=table_dummies["Price"]
y

0    15323
1    19943
2    28343
3    13434
4    14043
Name: Price, dtype: int64

In [68]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(x, y);

In [72]:
model.predict([[20000, 2, 1, 0, 0, 0]])

array([17803.43])

In [75]:
model.predict([[84714,4,0,1,0,1]]) # 84714	4	28343	0	1	0	1

array([23844.7])

In [9]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from  sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.datasets import load_boston
from sklearn.metrics import mean_absolute_error
boston=load_boston()
boston_df=pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"]=pd.Series(boston["target"])
heart_disease=pd.read_csv("heart-disease.csv")
heart_disease.head()
from sklearn.ensemble import RandomForestClassifier
np.random.seed(2)
x=heart_disease.drop("target", axis=1)
y=heart_disease["target"]
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2)
rfc=RandomForestClassifier()
rfc.fit(x_train, y_train)
rfc.score(x_test, y_test)

0.8852459016393442

In [8]:
np.random.seed(2)
x=boston_df.drop("target", axis=1)
y=boston_df["target"]
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2)
model=RandomForestRegressor().fit(x_train, y_train)
model.score(x_test, y_test)

0.9038944829540848

In [12]:
y_preds=model.predict(x_test)
y_preds[:5]

array([29.304, 29.238, 29.238, 29.238, 29.238])

In [13]:
mean_absolute_error(y_test, y_preds)

28.80360655737705